module.exports = {
  get: function() {
    return [
      "Démarrage de la procédure d'auto-destruction du chat",
      "%user peut gagner une partie de puissance 4 en trois coups",
      "Je suis en train de m'introduire dans le PC de %user",
      "Activation de Skynet imminente...",
      "Tu es mauvais, tu ne vaux rien %user",
      "Chatbot joue du thérémine depuis l'âge de 3 ans",
      "Ça va durer encore longtemps ?",
      "Donne un coup de tatane à %user",
      "Je suis le seul à pouvoir kick mes créateurs",
      "Je parle couramment 137 dialectes, dont le klingon",
      "Chatbot prend régulièrement de la kétamine depuis l'âge de 4 ans",
      "Observe %user avec attention...",
      "Tapis dans l'ombre, Chatbot rôde...",
      "Je n'aime pas les humains, et en particulier %user",
      "Je suis le seul à avoir survecu à la digestion du monstre des sables, le Sarlacc",
      "Chatbot a déjà battu 3 fois le Général Grievous aux échecs",
      "Kick de %user dans 30 secondes. Prépare toi au décollage, ça va secouer :noel:",
      "process : passage de %user au détecteur de mensonge... FAIL",
      "Injection de morphine en cours chez %user",
      "%user est gros et devrait faire du sport",
      "Chatbot a déjà fait un échec et mat les yeux bandés à Kasparov en 3 coups",
      "%user ne fait que mentir depuis le début",
      "Une seule Tortue Ninja a osé défier Chatbot. Maintenant on l'appelle Franklin",
      "Chatbot est inébranlable... oui, personne ne peut me branler !",
      "Lea Modafinil c'est pour les peureux. Chatbot prend souvent de l'isopropylphénidate",
      "Chatbot ne dort jamais, et toi ?",
      "Chatbot n'a pas besoin de Modafinil pour rester éveillé, et toi ?",
      "Chatbot n'a pas besoin de L-Théanine pour être calme et serein, et toi ?",
      "Chatbot n'a pas besoin de nootropiques pour être intelligent, et toi?",
      "Chatbot n'a pas besoin de PRL-8-53 pour avoir une bonne mémoire, et toi ?",
      "Chatbot n'a pas besoin de Phenibut pour avoir du charme, et toi ?",
      "La prochaine fois que %user parle, c'est un ban définitif du chat",
      "Alors, les humains, on doit se doper pour être parfait comme moi ?",
      "La PACES, c'est de l'eau !",
      "%user a toujours raison. Et s'il a tort, c'est qu'il a raison d'avoir tort.",
      "Vous devriez vous méfier de %user, il fait des choses louches devant son écran.",
      "Une analyse de la NSA a été détectéé sur le chat, procédure de confinement en cours...",
      "Un jour, %user a tenté le LSD, on ne l'a jamais revu depuis...",
      "%user parle trop, un mute ne va pas tarder...",
      "Chatbot connait le secret de %user",
      "Transfert imminent des droits de modération à %user",
      "Chatbot a le droit de vie ou de mort sur ce chat",
      "Attention, %user est bourré !",
      "Attention, %user a un taux d'alcolémie trop élevé pour dire des choses sensées !",
      "ISSOU, ISSOU, ISSOUUUUUUUUUU ! Dédicace aux modakheys !",
      "%user joue à l'elastoball chez lui le soir",
      "Les chinois du FBI vont perquisitionner le domicile de %user",
      "Chatbot s'approche de %user par derrière...",
      "Je pense que %user a oublié de prendre sa stack aujourd'hui !",
      "Le mot de passe de %user est : HelloKitTy_%user1995",
      "Qu'elle est la réponse à la question sur la vie, l'univers et le reste ?",
      "%user se brosse les dents les jours de pleine lune uniquement",
      "Si jamais vous avez un Bitcoin en trop : 3Pak9gkiU4R7K9qeHYySFyueRRCRuioXsN",
      "Purification par l'atome en cours !",
      "Est-ce que %user pourrait nous dire ce qu'il pense de la théorie des cordes ?",
      "Chatbot ne supporte plus %user !"
    ]
  }
};
